spring.application.name=HN_K24_CNTT3_DOHONGKY_005
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/showroom_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234567890

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true